# 实验1 机器学习实验基础(Numpy)

In [2]:
import numpy as np

# 1. 数据读取、数据属性

In [ ]:
print('Loading data ...')
# 1. 装载数据集
data = np.loadtxt('./house_price.txt', delimiter=',')

# 2. 打印数据集的维度数，及各维度的尺寸
print(data.shape, data.ndim)
print("Size of data is :",  , ", and dimension is",  )

# 3. 打印样本个数和样本维度
m = 
n = 
print(m, n)

# 2. 数据切片与检索

In [ ]:
#1. 读取前两列作为输入X

#2. 读取第3列作为y （一维数组）

#3. 读取第3列作为y （m*1的二维矩阵）

#4. 显示前10条房价数据

#5. 显示房价低于20万的房屋数据（for循环、逻辑表达式）


# 1. 数组创建
创建空数组、全零、全一、随机、序列数组

##### 1.1 空数据 numpy.empty(shape, dtype=float, order='C')
order：是否在内存中以C或fortran(C或F，行或列)顺序存储多维数据

In [ ]:
x1 = 
print(x1)

##### 1.2 全零 numpy.zeros(shape, dtype = float, order = 'C')，zeros_like()  

In [ ]:
x2 = 
print(x2)

##### 1.3 全一 numpy.ones(shape, dtype = None, order = 'C') 

In [ ]:
x3 = 
print(x3)

##### 1.4 随机 numpy.random.random()

In [15]:
x4 = np.random.random([3,2])
print(x4)

##### 1.5 生成序列

In [3]:
x5 = np.arange(9)
print(x5)

[0 1 2 3 4 5 6 7 8]


# 2. 数组操作 

##### 2.1 数组的转置
对X分别使用numpy.transpose(arr, axes)和numpy.ndarray.T进行转置

In [ ]:
X_T = 
print(X_T)

##### 2.2 数组拼接：numpy.vstack()和numpy.hstack()
为X数据添加X0=1的全一列

In [ ]:
# 为X数据增加X0=1的全一列
X_all = 

##### 2.3 reshape 不改变数据的情况下改变数组的形状
使用numpy.arange(9)reshape成(3*3)的数组

In [ ]:
x23 = np.arange(9)
x23.reshape(3,3)
print(x23)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

##### 2.4 flatten 返回一个数据展开后的拷贝，但不改变原本数组
ndarray.flatten(order='C')
将房价数据的标注y变成m*1的二维数组，然后再将二维数组使用flatten()函数展成一个一维数组。

In [ ]:
x24 = x23.flatten()
print(x24)

# 将房价数据的标注y变成m*1的二维数组

# 将m*1的二维数组y使用flatten()函数展成一个一维数组


# 3. 向量/矩阵运算
##### 3.1 向量点积和矩阵乘 numpy.dot()和@运算符
numpy.dot(a, b) 两个数组的点积，也可用于矩阵相乘。还可以用运算符@

In [ ]:
n = data.shape[1] - 1
w = np.ones((n + 1, 1))
X = X_all.T  #将每个样本以列向量的形式表示,X_all带全1列作为x0
# 计算w^T * X

##### 3.2 矩阵求逆 numpy.linalg.inv()
提供了线性代数(linear algebra)函数库 linalg，该库包含了线性代数所需的所有功能

In [ ]:
x32 = np.array([[1,2],[3,4]])
print(x32)


array([[-2. ,  1. ],
       [ 1.5, -0.5]])

##### 3.3 计算矩阵的行列式(determinant) numpy.linalg.det() 

In [ ]:
x33 = np.array([[0,1],[2,3]])
print(x33)